# Site Settings

name: Solid State

baseurl: "/solid-state" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: John Smith
  address:
    line1: 1234 Somewhere Road Suite #2894
    line2: Kelowna, BC V1X 2C4
  phone: (555) 555-5555

# Enter your Google Analytics web tracking code (starts with UA-* or G-* if using GA4)
google_analytics: G-EPSSK79JX4

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Paginate
paginate: 6
paginate_path: /page:num/

plugins:
  - jekyll-paginate

include: [_pages]